### ISSUE TITLE
Integración Continua para Rust con GitLab

### ISSUE THREAD

**Issue by mattdark** [rustmx/Charlas#11]
**Nombre de la propuesta**: Integración Continua para Rust con GitLab

**Descripción**: Si desarrollas aplicaciones con Rust y en especial web apps con algún framework como Rocket, usar un sistema de integración continua puede ayudarte a optimizar la ejecución de pruebas y la puesta en producción en servicios en la nube como Heroku. GitLab cuenta con un sistema de integración continua y otras herramientas que pueden ayudarte en este proceso, las cuales conocerás en esta charla.

**Objetivo**: A través de esta charla aprenderás a configurar el sistema de integración continua de GitLab y llevar tu proyecto a producción.

**Breve reseña sobre ti**: Usuario y contribuidor activo en proyectos de código abierto. Conferencista. Ha colaborado con Mozilla desde 2011 y es Mozilla Reps. Se unió a los programas GitLab Heroes y GitKraken Ambassadors en 2019. Desarrollador Web. Además, escribe artículos técnicos en dev.to.

**Correo electrónico**: hi@mariog.xyz

**Comment by mayela** [comment]
Cerrando issue. Muchas gracias por la charla @mattdark! :crab:
