### ISSUE TITLE
Rust aplicado a microVirtualización - AWS Firecracker

### ISSUE THREAD

**Issue by gusdelact** [rustmx/Charlas#12]
Nombre de la propuesta: Rust aplicado a microVirtualización - AWS Firecracker
Descripción: El modelo de cómputo serverless permite crear y ejecutar aplicaciones y servicios sin tener que preocuparse por el aprovisionamiento de servidores, el mantenimiento del sistema operativo. Puede crearlas para prácticamente cualquier tipo de aplicación o servicio de backend.
Para lograr eficiencias al respecto, el concepto de microVirtualización (microVM) . 
En el caso de la nube de Amazon, Firecracker es un monitor de maquina virtual virtual (VMM) que utiliza Linux Kernel-based Virtual Machine (KVM) para crear y manejar microVMs. 
Firecracker está desarrollado con el lenguaje de programación de Rust. 
En esta sesión se va explicar los conceptos fundamentales de Firecracker y revisar a un nivel básico, la estructura de los módulos del código.
Objetivo: Explicar el diseño de Firecracker y como Rust se utilizó para su implantación
Breve reseña sobre ti: Gustavo De la Cruz Tovar es desarrollador y arquitecto con experiencia en sistemas de backend. En su concepción actual se ha dado cuenta que en el diseño del software uno de los atributos prioritarios es el desempeño y poder aprovechar la potencia de computo. De ahí es que Rust ha sido un lenguaje que le ha motivado a continuar  con su hobbie de programador.
Correo electrónico: gusdelact@gmail.com

**Comment by mayela** [comment]
Programamos tu charla para octubre @gusdelact!

**Comment by mayela** [comment]
Mil gracias por la charla @gusdelact. Procedo a cerrar el issue
