### ISSUE TITLE
IoT con Rust, básicos para el mundo real 

### ISSUE THREAD

**Issue by phonnz** [rustmx/Charlas#13]
Nombre de la propuesta: **IoT con Rust, básicos para el mundo real** 

Descripción(en caso de ser propuesta): 
Actualmente tenemos presentes pequeños dispositivos de bajo costo y consumo de energía, que a su vez tienen recursos limitados, por lo que llevar el software para operarlos al nivel más alto es conveniente para el desempaño de las tareas.
Rust puede ser una gran opción debido a la seguridad del lenguaje y el alto desempeño que brinda.

Objetivo(aplica a todos): 
Mostrar como iniciar a trabajar con **ARM**, describir como se resuelven las **tareas básicas** de cualquier sistema IoT

Breve reseña sobre ti(en caso de ser propuesta): 
Entusiasta del Software y tecnología, trabajando en diseñar un sistema distribuido para IoT  para brindar una plataforma cashierless en la industria de retailers.

Correo electrónico: alfonso@intuitivo.ai

**Comment by mayela** [comment]
Gracias por la charla @phonnz! Cierro el issue
