### ISSUE TITLE
Extendiendo Ruby con Rust

### ISSUE THREAD

**Issue by chillicoder** [rustmx/Charlas#14]
Ruby es lenguaje interpretado orientado a hacer felices a los programadores, pero el costo asociado es que no es precisamente "rápido". ¿Podemos hacer más rápido a Ruby usando Rust?

**Comment by mayela** [comment]
Hola @chillicoder! Te gustaría dar tu charla en octubre? Espero tu respuesta, saludos

**Comment by mayela** [comment]
Muchas gracias por la charla @chillicoder. Procedo a cerrar el issue
