### ISSUE TITLE
CSCVSC: Tu framework de procesamiento de datos tabulados de confianza

### ISSUE THREAD

**Issue by categulario** [rustmx/Charlas#18]
**Nombre de la propuesta**: CSVSC, tu framework para procesamiento de datos tabulados de confianza
**Descripción**: Esta plática es la presentación en sociedad de un crate en el que he estado trabajando por algún tiempo, que sirve para trabajar con archivos CSV y hacer cosas impresionantes con ellos.
**Objetivo**: Dar a conocer el crate CSVSC
**Breve reseña sobre ti**: Matemático, programador y montañista que pasa los días haciendo huaraches y las noches echando el código.
**Correo electrónico**: categulario [at] gmail [dot] com

**Comment by mayela** [comment]
Muchas gracias @categulario por la charla. Procedo a cerrar el issue
