### ISSUE TITLE
Posada comunidad RustMX

### ISSUE THREAD

**Issue by gusdelact** [rustmx/Charlas#19]
Nombre de la propuesta: Posada comunidad RustMX
Descripción:  Cerramos el año platicando! Hagamos una charla con la comunidad. Propongo que platiquemos de:

Influencia de Rust en la industria de TI
Tipo de aplicaciones que se pueden construir con Rust 
Modelos de programación de sistemas al que nos lleva Rust
Que planeamos hacer para 2021 ?

Objetivo: Se nos va el 2020!  Es momento de platicar lo que sucedido con Rust ese año. Invitemos a contribuyentes de esta comunidad.
Breve reseña sobre ti: Gustavo De la Cruz Tovar es desarrollador y arquitecto con experiencia en sistemas de backend. En su concepción actual se ha dado cuenta que en el diseño del software uno de los atributos prioritarios es el desempeño y poder aprovechar la potencia de computo. De ahí es que Rust ha sido un lenguaje que le ha motivado a continuar con su hobbie de programador.
Correo electrónico: gusdelact@gmail.com

**Comment by mayela** [comment]
Muchas gracias @gusdelact por proponer esta actividad. Cierro el issue
