### ISSUE TITLE
TDD con Rust - nivel 100

### ISSUE THREAD

**Issue by chillicoder** [rustmx/Charlas#2]
Nombre de la propuesta: TDD con Rust - nivel 100
Descripción: Introducción a TDD con ejemplos sencillos y prácticos.
Objetivo(aplica a todos): Introducir a los programadores Rust a la práctica TDD
Breve reseña sobre ti: Me gusta programar :-)

**Comment by mayela** [comment]
Hola @chillicoder! Muchad gracias por tu propuesta, la podemos agendar para octubre?

**Comment by chillicoder** [comment]
Sin problema!

**Comment by mayela** [comment]
Listo, agendada para octubre. Te vemos en Red Hat!

**Comment by chillicoder** [comment]
👍

**Comment by mayela** [comment]
Hola @chillicoder, me pregunto si no tienes inconveniente en que se mueva la sesión para el miércoles 23 de octubre?
Saludos

**Comment by chillicoder** [comment]
Hola! Sin problema, me ajusto al calendario :-)

**Comment by mayela** [comment]
Gracias por la plática @chillicoder. Doy por cerrado este issue
