### ISSUE TITLE
Apache Kafka con Rust

### ISSUE THREAD

**Issue by uurl** [rustmx/Charlas#3]
- Nombre de la propuesta:     Apache Kafka con Rust
- Descripción(en caso de ser propuesta):                En la reunión de Big Data con Rust se habló de S.M.A.C.K. pero solo se enfocó a las opciones para Apache Spark. En esta reunión hablaremos de cómo usar Apache Kafka con Rust.
- Objetivo(aplica a todos):              Mostrar las diferentes opciones para usar Apache Kafka con Rust.
- Breve reseña sobre ti(en caso de ser propuesta):    Expone @rugi Isaac Ruiz Guerra es programador de Java desde 2001 y consultor de TI desde 2003. Isaac está especializado en integración de sistemas, ha participado en proyectos principalmente relacionados al sector financiero. Ha trabajado principalmente en el backend utilizando lenguajes como Java, Python y Elixir. Isaac es coautor del libro Big Data SMACK.
- Correo electrónico:                rugi.eolos@gmail.com
                                                     raulestradaa@gmail.com
- Es importante que esta charla sea a fines de Noviembre 2019.

**Comment by gusdelact** [comment]
Excelente!!  Esto abre el camino a una posible plática para 2020 sobre implantar BigData con el modelo que propones pero basado en Rust. En efecto, se expuso sobre Spark pero también la implantación de Apache Arrow, también ya se habló de Actix para el modelo actores. Con tu platica tenemos para hablar del tercer componente - Kafka -

**Comment by mayela** [comment]
gracias a Rugi por la charla! Cierro issue
