### ISSUE TITLE
Teoría de tipos

### ISSUE THREAD

**Issue by Vicfred** [rustmx/Charlas#4]
- **Nombre de la propuesta**: Teoría de tipos

- **Descripción**: El sistema de tipos de Rust fue influenciado la familia de lenguajes ML, veremos como usar los tipos a nuestro favor.

- **Objetivo**: Introducirse a la teoría de tipos mediante ejemplos.

- **Breve reseña sobre ti**: Me gusta la matemagia y las compus.

- Correo electrónico: vicfred@vicfred.dev

**Comment by mayela** [comment]
Gracias @Vicfred! Ya lo agendamos para el 27 noviembre. Nos vemos allá

**Comment by mayela** [comment]
Gracias @Vicfred por tu charla! Cierro el issue
