### ISSUE TITLE
Iniciando el año con Rust

### ISSUE THREAD

**Issue by gusdelact** [rustmx/Charlas#5]
- Nombre de la propuesta:  Iniciando el 2020 con Rust

-  Descripción.  Un nuevo año ha iniciado!  En esta sesión es darauna introducción a Rust y sus principales características tales como:

- Tipos de datos
- Modelo de memoria, conceptos propiedad y préstamo.
- Enumeraciones y pattern matching
- Modularizando con Crates
- Tipos genéricos, Tratos, tiempo de vida 

Objetivo(aplica a todos): Introducir a los asistentes que son nuevos al lenguaje o a la comunidad, sobre Rust.

Breve reseña sobre ti: Me gusta programar por hobbie y para dar soluciones. Trabajo en Amazon Web Services. Llevo colaborando con la comunidad RustMX desde agosto 2017.

**Comment by mayela** [comment]
Gracias @gusdelact! Queda programada para el 22 de enero

**Comment by mayela** [comment]
Gracias @gusdelact por la charla. Procedo a cerrar el issue
