### ISSUE TITLE
Construyendo un "pipeline" para Rust

### ISSUE THREAD

**Issue by chillicoder** [rustmx/Charlas#6]
Les quiero platicar como se construye un pipeline para Rust usando el ejemplo de un _crate_. El objetivo es automatizar la construcción de artefactos Rust.

**Comment by mayela** [comment]
@chillicoder Te interesa dar esta propuesta en la reunión de agosto? Saludos

**Comment by chillicoder** [comment]
¡Si! Me parece perfecto! 😄

**Comment by mayela** [comment]
Gracias por la charla @chillicoder! Cierro el issue

**Comment by chillicoder** [comment]
¡Un gusto!
