### ISSUE TITLE
Introducción al manejo de memoria con Rust

### ISSUE THREAD

**Issue by gusdelact** [rustmx/Charlas#7]
Nombre de la propuesta: Introducción al manejo de memoria con Rust
Descripción: Ilustrar con ejemplos de código, la manera en la que Rust maneja la memoria.

- Modelo de memoria
- Propiedad
- Préstamo.
- Tiempo de Vida

Objetivo: 
Breve reseña sobre ti(en caso de ser propuesta):  Introducir a los asistentes que son nuevos al lenguaje o a la comunidad, sobre el manejo de memoria de  Rust.

Correo electrónico: gusdelact@gmail.com

**Comment by mayela** [comment]
Recuerdo que de este issue todavía hay temas por abarcar, cierto @gusdelact ?

**Comment by mayela** [comment]
Cerrando issue. @gusdelact muchas gracias por la charla! :crab:
