### ISSUE TITLE
Organizando código Rusts con Crates

### ISSUE THREAD

**Issue by gusdelact** [rustmx/Charlas#8]
Nombre de la propuesta: Organizando código Rusts con Crates
Descripción: Ilustrar como se organiza el código de Rust para ser modular y poder compartirlo como paquetes.
Paquetes
Crates
Módulos
Objetivo: Introducir a los asistentes que son nuevos al lenguaje o a la comunidad, sobre como escribir paquetes en Rust; así como entender las técnicas para obtener módulos de código.
Correo electrónico: gusdelact@gmail.com

**Comment by mayela** [comment]
Gracias por la charla! Procedo a cerrar el issue
