### ISSUE TITLE
Regalos del colector estático de basura y de Rc<T> a mi algoritmo de map matching

### ISSUE THREAD

**Issue by categulario** [rustmx/Charlas#9]
Nombre de la propuesta: Regalos del colector estático de basura y de Rc<T> a mi algoritmo de map matching
Descripción(en caso de ser propuesta): Aparte de las conocidas ventajas del bajo consumo de recursos, ¿Qué otras maravillas nos esperan en este lenguaje? Una pequeña muestra de optimizaciones que de otra manera serían difíciles o peligrosas.
Objetivo(aplica a todos): Mostrar con ejemplos concretos cómo el diseño del lenguaje permite optimizaciones insospechadas en el código
Breve reseña sobre ti(en caso de ser propuesta): Matemático, programador y montañista que fabrica sus propios huaraches
Correo electrónico: categulario@gmail.com

**Comment by mayela** [comment]
Hola @categulario podemos tener tu charla el miércoles 22 de abril?

**Comment by categulario** [comment]
Claro!

**Comment by mayela** [comment]
Cerrando issue. @categulario muchas gracias por la charla! :crab:
